### ISSUE TITLE
https://github.com/evergreen-ci/evergreen/wiki/Getting-Started

### ISSUE THREAD

**Issue by bsmita** [evergreen-ci/evergreen#11]
Hi
On evergreen wiki page, https://github.com/evergreen-ci/evergreen/wiki/Getting-Started
the link "For information on configuring a static provider along with a "localhost" tutorial, click here."
When I clicked on "here" it goes to a TODO page. Can you please provide more instructions on how to setup the web UI's for evergreen and how to make the agents between Master/slaves talk to each other ? Thanks!

**Comment by bsmita** [comment]
Any updates on this issue?

**Comment by 3rf** [comment]
Hi bsmita,

I'm sorry that the tutorials and examples are not fully filled in at this time. Things were in flux as the original documentation was written and we chose to delay writing any detailed tutorials in our alpha release. I will try and get a decent localhost tutorial up in the next few days.

Thank you for your patience,
Kyle

**Comment by bsmita** [comment]
Thank you for the response. If you prefer sending the instructions through email before updating the page, my email is bsmita@us.ibm.com

**Comment by 3rf** [comment]
I'll be spending today fleshing out the documentation. Here's how I plan to proceed: I'm going to update the wiki documentation here on Github and then check in with you over email so I can answer any questions you have and work through any issues directly.

Looking forward to it!
Kyle

**Comment by bsmita** [comment]
Thank you!

**Comment by 3rf** [comment]
Sent you and email. Thank you again for your patience.

I'm sure the documentation will be immeasurably better once we work through this!

**Comment by 3rf** [comment]
There is always more documentation work to be done. However, the current documentation links to a real tutorial now, and those questions should be answered.
