### ISSUE TITLE
General git support (not GitHub)

### ISSUE THREAD

**Issue by joelsand** [evergreen-ci/evergreen#4]
Love the approach to CI and running integration tests you're taking on this project.

Maybe I missed it, but it appears from evergreen/docs/evg_example_config.yml and the "Getting Started" documentation that it requires the repositories be in GitHub. Any support or future plans for supporting general git repositories (e.g. Atlassian Stash)?

**Comment by mpobrien** [comment]
This is definitely high on the list, hoping to get to it soon. We're investigating using [libgit2](https://libgit2.github.com/) for this if possible.

**Comment by IanWhalen** [comment]
tracking in https://jira.mongodb.org/browse/EVG-218

**Comment by ramonfm** [comment]
Closing this since we have a JIRA ticket to track this request.
