### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by yellowmegaman** [evergreen-ci/evergreen#41]
Hello! I'd like to try to setup and use your CI server, but lack of skills in golang compiling/developing got me stuck right at the beginning.

I've got my gopath set, and other projects compile nicely (hashicorp tools mostly).
But here i got this:

```
evergreen$ ./build.sh 
go build -o bin/render-gopath scripts/render-gopath.go
go build -o bin/make-vendor scripts/make-vendor.go
can use existing (new-style) vendoring configuration
make: *** No rule to make target 'Plugins', needed by 'bin/.plugins'.  Stop.
```

Any advice?
Thanks!

P.S. https://evergreen.mongodb.com looks awesome, hoping there's a lot of yml greatness under the hood ;)

**Comment by tychoish** [comment]
ah, sorry for the confusion. I'll open a ticket in our Jira tracker to address this, but as a quick workaround, you can simply touch the Plugins file, e.g.

    touch Plugins

and the build will work fine.

**Comment by tychoish** [comment]
That issue is: https://jira.mongodb.org/browse/EVG-1401

**Comment by yellowmegaman** [comment]
Thanks a lot for your time. Seems i'm lost again though. 
After reading main README.md i came to understanding that deps are managed by glide, so that's what i got so far:
http://pastebin.com/QNyVCQua

**Comment by yellowmegaman** [comment]
Agent building ok.

**Comment by ramonfm** [comment]
Looks like we forgot to close this issue after addressing it; closing it now.
