### ISSUE TITLE
User time zones - add GMT

### ISSUE THREAD

**Issue by braz** [evergreen-ci/evergreen#48]
Hi All,

Is it possible to add some additional locales to the user settings page for Evergreen such that you could include GMT ? Dublin / London don't appear to fall within the existing set of time zones. Thanks!

Eoin

**Comment by ramonfm** [comment]
@braz , can you please [open a ticket in the EVG project](https://jira.mongodb.org/secure/CreateIssue!default.jspa?pid=12787)?

Thanks,
Ramón.
